export const iconsLink = [
    { icon: "pi pi-facebook", name: "Facebook" },
    { icon: "pi pi-whatsapp", name: "Whatsapp" },
    { icon: "pi pi-twitter", name: "Twitter" },
    { icon: "pi pi-reddit", name: "Reddit" },
    { icon: "pi pi-linkedin", name: "Linkedin" },
    { icon: "pi pi-instagram", name: "Instagram" },
    { icon: "pi pi-github", name: "Github" },
    { icon: "pi pi-vimeo", name: "Vimeo" },
    { icon: "pi pi-youtube", name: "Youtube" },
    { icon: "pi pi-discord", name: "Discord" },
]

export const allIcons = [
    { icon: "pi-align-center", name: "Align Center" },
    { icon: "pi-align-justify", name: "Align Justify" },
    { icon: "pi-align-left", name: "Align Left" },
    { icon: "pi-align-right", name: "Align Right" },
    { icon: "pi-amazon", name: "Amazon" },
    { icon: "pi-android", name: "Android" },
    { icon: "pi-angle-double-down", name: "Angle Double Down" },
    { icon: "pi-angle-double-left", name: "Angle Double Left" },
    { icon: "pi-angle-double-right", name: "Angle Double Right" },
    { icon: "pi-angle-double-up", name: "Angle Double Up" },
    { icon: "pi-angle-down", name: "Angle Down" },
    { icon: "pi-angle-left", name: "Angle Left" },
    { icon: "pi-angle-right", name: "Angle Right" },
    { icon: "pi-angle-up", name: "Angle Up" },
    { icon: "pi-apple", name: "Apple" },
    { icon: "pi-arrow-circle-down", name: "Arrow Circle Down" },
    { icon: "pi-arrow-circle-left", name: "Arrow Circle Left" },
    { icon: "pi-arrow-circle-right", name: "Arrow Circle Right" },
    { icon: "pi-arrow-circle-up", name: "Arrow Circle Up" },
    { icon: "pi-arrow-down", name: "Arrow Down" },
    { icon: "pi-arrow-down-left", name: "Arrow Down Left" },
    { icon: "pi-arrow-down-right", name: "Arrow Down Right" },
    { icon: "pi-arrow-left", name: "Arrow Left" },
    { icon: "pi-arrow-right", name: "Arrow Right" },
    { icon: "pi-arrow-right-arrow-left", name: "Arrow Right Arrow Left" },
    { icon: "pi-arrow-up", name: "Arrow Up" },
    { icon: "pi-arrow-up-left", name: "Arrow Up Left" },
    { icon: "pi-arrow-up-right", name: "Arrow Up Right" },
    { icon: "pi-arrows-alt", name: "Arrows Alt" },
    { icon: "pi-arrows-h", name: "Arrows H" },
    { icon: "pi-arrows-v", name: "Arrows V" },
    { icon: "pi-at", name: "At" },
    { icon: "pi-backward", name: "Backward" },
    { icon: "pi-ban", name: "Ban" },
    { icon: "pi-bars", name: "Bars" },
    { icon: "pi-bell", name: "Bell" },
    { icon: "pi-bitcoin", name: "Bitcoin" },
    { icon: "pi-bolt", name: "Bolt" },
    { icon: "pi-book", name: "Book" },
    { icon: "pi-bookmark", name: "Bookmark" },
    { icon: "pi-bookmark-fill", name: "Bookmark Fill" },
    { icon: "pi-box", name: "Box" },
    { icon: "pi-briefcase", name: "Briefcase" },
    { icon: "pi-building", name: "Building" },
    { icon: "pi-calculator", name: "Calculator" },
    { icon: "pi-calendar", name: "Calendar" },
    { icon: "pi-calendar-minus", name: "Calendar Minus" },
    { icon: "pi-calendar-plus", name: "Calendar Plus" },
    { icon: "pi-calendar-times", name: "Calendar Times" },
    { icon: "pi-camera", name: "Camera" },
    { icon: "pi-car", name: "Car" },
    { icon: "pi-caret-down", name: "Caret Down" },
    { icon: "pi-caret-left", name: "Caret Left" },
    { icon: "pi-caret-right", name: "Caret Right" },
    { icon: "pi-caret-up", name: "Caret Up" },
    { icon: "pi-cart-plus", name: "Cart Plus" },
    { icon: "pi-chart-bar", name: "Chart Bar" },
    { icon: "pi-chart-line", name: "Chart Line" },
    { icon: "pi-chart-pie", name: "Chart Pie" },
    { icon: "pi-check", name: "Check" },
    { icon: "pi-check-circle", name: "Check Circle" },
    { icon: "pi-check-square", name: "Check Square" },
    { icon: "pi-chevron-circle-down", name: "Chevron Circle Down" },
    { icon: "pi-chevron-circle-left", name: "Chevron Circle Left" },
    { icon: "pi-chevron-circle-right", name: "Chevron Circle Right" },
    { icon: "pi-chevron-circle-up", name: "Chevron Circle Up" },
    { icon: "pi-chevron-down", name: "Chevron Down" },
    { icon: "pi-chevron-left", name: "Chevron Left" },
    { icon: "pi-chevron-right", name: "Chevron Right" },
    { icon: "pi-chevron-up", name: "Chevron Up" },
    { icon: "pi-circle", name: "Circle" },
    { icon: "pi-circle-fill", name: "Circle Fill" },
    { icon: "pi-clock", name: "Clock" },
    { icon: "pi-clone", name: "Clone" },
    { icon: "pi-cloud", name: "Cloud" },
    { icon: "pi-cloud-download", name: "Cloud Download" },
    { icon: "pi-cloud-upload", name: "Cloud Upload" },
    { icon: "pi-code", name: "Code" },
    { icon: "pi-cog", name: "Cog" },
    { icon: "pi-comment", name: "Comment" },
    { icon: "pi-comments", name: "Comments" },
    { icon: "pi-compass", name: "Compass" },
    { icon: "pi-copy", name: "Copy" },
    { icon: "pi-credit-card", name: "Credit Card" },
    { icon: "pi-database", name: "Database" },
    { icon: "pi-delete-left", name: "Delete Left" },
    { icon: "pi-desktop", name: "Desktop" },
    { icon: "pi-directions", name: "Directions" },
    { icon: "pi-directions-alt", name: "Directions Alt" },
    { icon: "pi-discord", name: "Discord" },
    { icon: "pi-dollar", name: "Dollar" },
    { icon: "pi-download", name: "Download" },
    { icon: "pi-eject", name: "Eject" },
    { icon: "pi-ellipsis-h", name: "Ellipsis H" },
    { icon: "pi-ellipsis-v", name: "Ellipsis V" },
    { icon: "pi-envelope", name: "Envelope" },
    { icon: "pi-eraser", name: "Eraser" },
    { icon: "pi-euro", name: "Euro" },
    { icon: "pi-exclamation-circle", name: "Exclamation Circle" },
    { icon: "pi-exclamation-triangle", name: "Exclamation Triangle" },
    { icon: "pi-external-link", name: "External Link" },
    { icon: "pi-eye", name: "Eye" },
    { icon: "pi-eye-slash", name: "Eye Slash" },
    { icon: "pi-facebook", name: "Facebook" },
    { icon: "pi-fast-backward", name: "Fast Backward" },
    { icon: "pi-fast-forward", name: "Fast Forward" },
    { icon: "pi-file", name: "File" },
    { icon: "pi-file-edit", name: "File Edit" },
    { icon: "pi-file-excel", name: "File Excel" },
    { icon: "pi-file-export", name: "File Export" },
    { icon: "pi-file-import", name: "File Import" },
    { icon: "pi-file-pdf", name: "File PDF" },
    { icon: "pi-file-word", name: "File Word" },
    { icon: "pi-filter", name: "Filter" },
    { icon: "pi-filter-fill", name: "Filter Fill" },
    { icon: "pi-filter-slash", name: "Filter Slash" },
    { icon: "pi-flag", name: "Flag" },
    { icon: "pi-flag-fill", name: "Flag Fill" },
    { icon: "pi-folder", name: "Folder" },
    { icon: "pi-folder-open", name: "Folder Open" },
    { icon: "pi-forward", name: "Forward" },
    { icon: "pi-gift", name: "Gift" },
    { icon: "pi-github", name: "GitHub" },
    { icon: "pi-globe", name: "Globe" },
    { icon: "pi-google", name: "Google" },
    { icon: "pi-hashtag", name: "Hashtag" },
    { icon: "pi-heart", name: "Heart" },
    { icon: "pi-heart-fill", name: "Heart Fill" },
    { icon: "pi-history", name: "History" },
    { icon: "pi-home", name: "Home" },
    { icon: "pi-hourglass", name: "Hourglass" },
    { icon: "pi-id-card", name: "ID Card" },
    { icon: "pi-image", name: "Image" },
    { icon: "pi-images", name: "Images" },
    { icon: "pi-inbox", name: "Inbox" },
    { icon: "pi-info", name: "Info" },
    { icon: "pi-info-circle", name: "Info Circle" },
    { icon: "pi-instagram", name: "Instagram" },
    { icon: "pi-key", name: "Key" },
    { icon: "pi-language", name: "Language" },
    { icon: "pi-link", name: "Link" },
    { icon: "pi-linkedin", name: "LinkedIn" },
    { icon: "pi-list", name: "List" },
    { icon: "pi-lock", name: "Lock" },
    { icon: "pi-lock-open", name: "Lock Open" },
    { icon: "pi-map", name: "Map" },
    { icon: "pi-map-marker", name: "Map Marker" },
    { icon: "pi-megaphone", name: "Megaphone" },
    { icon: "pi-microphone", name: "Microphone" },
    { icon: "pi-microsoft", name: "Microsoft" },
    { icon: "pi-minus", name: "Minus" },
    { icon: "pi-minus-circle", name: "Minus Circle" },
    { icon: "pi-mobile", name: "Mobile" },
    { icon: "pi-money-bill", name: "Money Bill" },
    { icon: "pi-moon", name: "Moon" },
    { icon: "pi-palette", name: "Palette" },
    { icon: "pi-paperclip", name: "Paperclip" },
    { icon: "pi-pause", name: "Pause" },
    { icon: "pi-paypal", name: "Paypal" },
    { icon: "pi-pencil", name: "Pencil" },
    { icon: "pi-percentage", name: "Percentage" },
    { icon: "pi-phone", name: "Phone" },
    { icon: "pi-play", name: "Play" },
    { icon: "pi-plus", name: "Plus" },
    { icon: "pi-plus-circle", name: "Plus Circle" },
    { icon: "pi-pound", name: "Pound" },
    { icon: "pi-power-off", name: "Power Off" },
    { icon: "pi-prime", name: "Prime" },
    { icon: "pi-print", name: "Print" },
    { icon: "pi-qrcode", name: "QR Code" },
    { icon: "pi-question", name: "Question" },
    { icon: "pi-question-circle", name: "Question Circle" },
    { icon: "pi-reddit", name: "Reddit" },
    { icon: "pi-refresh", name: "Refresh" },
    { icon: "pi-replay", name: "Replay" },
    { icon: "pi-reply", name: "Reply" },
    { icon: "pi-save", name: "Save" },
    { icon: "pi-search", name: "Search" },
    { icon: "pi-search-minus", name: "Search Minus" },
    { icon: "pi-search-plus", name: "Search Plus" },
    { icon: "pi-send", name: "Send" },
    { icon: "pi-server", name: "Server" },
    { icon: "pi-share-alt", name: "Share Alt" },
    { icon: "pi-shield", name: "Shield" },
    { icon: "pi-shopping-bag", name: "Shopping Bag" },
    { icon: "pi-shopping-cart", name: "Shopping Cart" },
    { icon: "pi-sign-in", name: "Sign In" },
    { icon: "pi-sign-out", name: "Sign Out" },
    { icon: "pi-sitemap", name: "Sitemap" },
    { icon: "pi-slack", name: "Slack" },
    { icon: "pi-sliders-h", name: "Sliders H" },
    { icon: "pi-sliders-v", name: "Sliders V" },
    { icon: "pi-sort", name: "Sort" },
    { icon: "pi-sort-alpha-down", name: "Sort Alpha Down" },
    { icon: "pi-sort-alpha-down-alt", name: "Sort Alpha Down Alt" },
    { icon: "pi-sort-alpha-up", name: "Sort Alpha Up" },
    { icon: "pi-sort-alpha-up-alt", name: "Sort Alpha Up Alt" },
    { icon: "pi-sort-alt", name: "Sort Alt" },
    { icon: "pi-sort-alt-slash", name: "Sort Alt Slash" },
    { icon: "pi-sort-amount-down", name: "Sort Amount Down" },
    { icon: "pi-sort-amount-down-alt", name: "Sort Amount Down Alt" },
    { icon: "pi-sort-amount-up", name: "Sort Amount Up" },
    { icon: "pi-sort-amount-up-alt", name: "Sort Amount Up Alt" },
    { icon: "pi-sort-down", name: "Sort Down" },
    { icon: "pi-sort-numeric-down", name: "Sort Numeric Down" },
    { icon: "pi-sort-numeric-down-alt", name: "Sort Numeric Down Alt" },
    { icon: "pi-sort-numeric-up", name: "Sort Numeric Up" },
    { icon: "pi-sort-numeric-up-alt", name: "Sort Numeric Up Alt" },
    { icon: "pi-sort-up", name: "Sort Up" },
    { icon: "pi-spinner", name: "Spinner" },
    { icon: "pi-star", name: "Star" },
    { icon: "pi-star-fill", name: "Star Fill" },
    { icon: "pi-step-backward", name: "Step Backward" },
    { icon: "pi-step-backward-alt", name: "Step Backward Alt" },
    { icon: "pi-step-forward", name: "Step Forward" },
    { icon: "pi-step-forward-alt", name: "Step Forward Alt" },
    { icon: "pi-stop", name: "Stop" },
    { icon: "pi-stop-circle", name: "Stop Circle" },
    { icon: "pi-stopwatch", name: "Stopwatch" },
    { icon: "pi-sun", name: "Sun" },
    { icon: "pi-sync", name: "Sync" },
    { icon: "pi-table", name: "Table" },
    { icon: "pi-tablet", name: "Tablet" },
    { icon: "pi-tag", name: "Tag" },
    { icon: "pi-tags", name: "Tags" },
    { icon: "pi-telegram", name: "Telegram" },
    { icon: "pi-th-large", name: "Th Large" },
    { icon: "pi-thumbs-down", name: "Thumbs Down" },
    { icon: "pi-thumbs-down-fill", name: "Thumbs Down Fill" },
    { icon: "pi-thumbs-up", name: "Thumbs Up" },
    { icon: "pi-thumbs-up-fill", name: "Thumbs Up Fill" },
    { icon: "pi-ticket", name: "Ticket" },
    { icon: "pi-times", name: "Times" },
    { icon: "pi-times-circle", name: "Times Circle" },
    { icon: "pi-trash", name: "Trash" },
    { icon: "pi-truck", name: "Truck" },
    { icon: "pi-twitter", name: "Twitter" },
    { icon: "pi-undo", name: "Undo" },
    { icon: "pi-unlock", name: "Unlock" },
    { icon: "pi-upload", name: "Upload" },
    { icon: "pi-user", name: "User" },
    { icon: "pi-user-edit", name: "User Edit" },
    { icon: "pi-user-minus", name: "User Minus" },
    { icon: "pi-user-plus", name: "User Plus" },
    { icon: "pi-users", name: "Users" },
    { icon: "pi-verified", name: "Verified" },
    { icon: "pi-video", name: "Video" },
    { icon: "pi-vimeo", name: "Vimeo" },
    { icon: "pi-volume-down", name: "Volume Down" },
    { icon: "pi-volume-off", name: "Volume Off" },
    { icon: "pi-volume-up", name: "Volume Up" },
    { icon: "pi-wallet", name: "Wallet" },
    { icon: "pi-whatsapp", name: "WhatsApp" },
    { icon: "pi-wifi", name: "WiFi" },
    { icon: "pi-window-maximize", name: "Window Maximize" },
    { icon: "pi-window-minimize", name: "Window Minimize" },
    { icon: "pi-wrench", name: "Wrench" },
    { icon: "pi-youtube", name: "YouTube" },
]
